spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: jwe-auth-service

security:
  jwt:
    keys:
      hmac:
        secret: ${JWT_HS512_SECRET}
      encrypt:
        private-key: ${ENCRYPT_PRIVATE_KEY}
        public-key: ${ENCRYPT_PUBLIC_KEY}
    claims:
      issuer: "demo1"
      audience: "demo-service"
      required-claims: [ "sub", "exp", "jti", "role" ]